Fix crash when analyzing shaders in devkit
clshortfuse/renodx pull request #16
Opened 2024-06-23 23:52 UTC by Filoppi

the functions were returning a char pointer within an object that might have already been destroyed

2024-06-24 14:27 UTC, clshortfuse requested changes

2024-06-24 14:27 UTC, clshortfuse commented on src/utils/shaderCompiler.hpp
>      if (result == nullptr) {
Not sure this will break DXC. Will result be `nullptr` if it fails?

2024-06-24 14:27 UTC, clshortfuse commented on src/devkit/addon.cpp
> +    delete newSubobjects;
This doesn't seem related

2024-06-24 14:27 UTC, clshortfuse commented on src/devkit/addon.cpp
> +        delete code;
`free` should be tied to `malloc` usage, not `delete`.

https://www.geeksforgeeks.org/delete-and-free-in-cpp/

But the flaw is likely here in that `code` isn't set to `nullptr`/`NULL` after being freed, so when it gets passed around, it still has the wrong pointer reference.

2024-06-24 14:27 UTC, clshortfuse commented on src/devkit/addon.cpp
> -                if (disasmCode == nullptr) {
I'm pretty sure this is the source of the crash. `disasmCode` is freed with `free` but the point is never rewritten, so it's never `nullptr` on crash.

2024-06-24 14:38 UTC, Filoppi commented on src/utils/shaderCompiler.hpp
>      if (result == nullptr) {
yes

2024-06-24 14:38 UTC, Filoppi commented on src/devkit/addon.cpp
> +    delete newSubobjects;
it's not. I just replaced all free with delete. AFAIK it's always better?

2024-06-24 14:40 UTC, Filoppi commented on src/devkit/addon.cpp
> -                if (disasmCode == nullptr) {
the source of the crash is that the `ID3DBlob` could end up being de-allocated at any time, and we were trying to "free" it ourselves, which isn't allowed. `ID3DBlob` lifespan needs to be handled with `CComPtr<ID3DBlob>`.

2024-06-24 16:36 UTC, clshortfuse commented on src/devkit/addon.cpp
> -                if (disasmCode == nullptr) {
That's not true. The Blob gets copied and released.

2024-06-24 17:41 UTC, Filoppi commented on src/devkit/addon.cpp
> -                if (disasmCode == nullptr) {
It wasn't ever released.

2024-06-25 00:48 UTC, clshortfuse commented on src/devkit/addon.cpp
> -                if (disasmCode == nullptr) {
You're, right I was looking at `compileShaderFromFileFXC` which does copy the output

2024-06-25 00:59 UTC, closed without merging